# Generated by Django 5.2.6 on 2025-09-20 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='demand_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='entry_level_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='growth_rate',
            field=models.CharField(blank=True, help_text='e.g., +15%', max_length=10),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='mid_level_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='senior_level_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PersonalizedRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('learning_style', models.CharField(choices=[('self_paced', 'Self-Paced Courses'), ('bootcamp', 'Bootcamps'), ('certification', 'Certifications'), ('mixed', 'Mixed Approach')], default='mixed', max_length=50)),
                ('hours_per_week', models.IntegerField(default=10, help_text='Available study hours per week')),
                ('estimated_completion_weeks', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('target_completion_date', models.DateTimeField(blank=True, null=True)),
                ('current_phase', models.CharField(default='Foundation', max_length=100)),
                ('overall_progress_percentage', models.FloatField(default=0.0)),
                ('job_readiness_score', models.IntegerField(default=0, help_text='Score 0-100 for job readiness')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roadmaps', to='careers.careerpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'target_career')},
            },
        ),
        migrations.CreateModel(
            name='CareerProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_milestones', models.IntegerField(default=0)),
                ('total_milestones', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('job_readiness_score', models.IntegerField(default=0)),
                ('skills_acquired', models.JSONField(default=list)),
                ('time_spent_hours', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='careers.personalizedroadmap')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(default='intermediate', max_length=50)),
                ('repo_template_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_recommendations', to='careers.careerpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phase', models.CharField(choices=[('Foundation', 'Foundation (0-3 months)'), ('Intermediate', 'Intermediate (3-6 months)'), ('Advanced', 'Advanced (6-12 months)'), ('Specialization', 'Specialization (12+ months)')], max_length=100)),
                ('order_in_phase', models.IntegerField(default=0)),
                ('estimated_hours', models.IntegerField(default=10)),
                ('estimated_weeks', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='careers.roadmapmilestone')),
                ('related_skills', models.ManyToManyField(blank=True, to='skills.skill')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='careers.personalizedroadmap')),
            ],
            options={
                'ordering': ['phase', 'order_in_phase'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('course', 'Online Course'), ('book', 'Book'), ('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('video', 'Video'), ('practice', 'Practice Platform'), ('project', 'Project Template'), ('certification', 'Certification'), ('bootcamp', 'Bootcamp')], max_length=50)),
                ('url', models.URLField(blank=True)),
                ('provider', models.CharField(blank=True, help_text='e.g., Coursera, Udemy, YouTube', max_length=100)),
                ('cost_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('freemium', 'Freemium')], default='free', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('rating', models.FloatField(blank=True, help_text='User rating 0-5', null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='careers.roadmapmilestone')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_hours', models.PositiveIntegerField(default=4)),
                ('resource_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='careers.careerpath')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_skills', models.JSONField(default=dict, help_text='Current skills with levels')),
                ('required_skills', models.JSONField(default=dict, help_text='Required skills for target career')),
                ('missing_skills', models.JSONField(default=list, help_text='List of missing skills')),
                ('weak_skills', models.JSONField(default=list, help_text='Skills below required level')),
                ('strong_skills', models.JSONField(default=list, help_text='Skills above required level')),
                ('skill_match_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analysis', to='careers.personalizedroadmap')),
            ],
        ),
    ]
